#!/usr/bin/env python

import sys

MAX = 140
count = sum(len(line) for line in open('generate') if not line.startswith('#'))
if count > MAX:
    sys.exit('Too large: ' + str(count) + ' characters')
else:
    print 'All is good, only', count, 'characters'
