#!/usr/bin/env python
# Diceware password generator in Python, in one tweet.
# (words file is http://world.std.com/~reinhold/beale.wordlist.asc)
# Because I have no dice:
import random
w = [s.split()[1] for s in open('words') if s[0] in '123456']
for i in range(5): print random.SystemRandom().choice(w),
