#!/usr/bin/env python
# Diceware password generator in Python, in one tweet.
# (words file is https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt)
# Because I have no dice:
import random, sys
w = [s.split()[1] for s in open(sys.path[0]+'/words')]
print '-'.join(random.SystemRandom().choice(w) for i in range(5))
